// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * `database.create` — make sure a database and an account for it exist on one instance.
 */
export type DatabaseCreate = { 
/**
 * Which instance: `mariadb@main`, `postgres@shop`.
 */
service: ServiceId, 
/**
 * The database's name.
 */
database: string, 
/**
 * The account's name. The database's own name when nobody says.
 */
user?: string | null, };
