// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeKind } from "./RuntimeKind";

/**
 * Which runtimes a listing should answer with.
 *
 * Every field has a default, so both listings with no parameters are questions a person can type.
 */
export type RuntimeFilter = { 
/**
 * Only this language, or all of them.
 *
 * A filter rather than a required argument because "what is installed" is a question a GUI's
 * first paint asks about everything at once, and because the answer for a kind nobody has
 * installed is an empty list rather than an error.
 */
kind?: RuntimeKind | null, };
