// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { ServiceState } from "./ServiceState";
import type { Timestamp } from "./Timestamp";

/**
 * One service, as the daemon currently sees it. Also the whole of what `service.status` answers.
 *
 * One type for the list and for the single lookup on purpose: they are the same sentence about a
 * service, so a client renders them with one function and a field added here reaches both.
 */
export type ServiceSummary = { 
/**
 * Which service this is.
 */
id: ServiceId, 
/**
 * What the `services` row says it is doing.
 *
 * **[`None`] means declared but never created**: something describes how to run this service
 * and the daemon has no row for it, so it has no state to be in and cannot be started until one
 * exists. Not a case a finished MixEngine reaches — from T30 onwards a declaration is *rendered
 * from* a row — which is exactly why it is reported rather than smoothed over into `stopped`: a
 * service that quietly claims to be stopped and then refuses to start explains nothing.
 */
state?: ServiceState | null, 
/**
 * Whether a task in this daemon is supervising it right now.
 *
 * Not a second opinion about [`ServiceSummary::state`] — the row is the only thing that says
 * what a service is doing — but the answer to a different question: a row saying `running` with
 * nothing supervising it is what a daemon that was killed leaves behind, and adopting or
 * clearing those is T18. Until then this is where that gap is visible instead of implied.
 */
supervised: boolean, 
/**
 * The process it is running as, where there is one.
 */
pid: number | null, 
/**
 * The port its row was given, and [`None`] for a service that listens on none.
 *
 * **The number in the row, not one derived from the running process** — roadmap task
 * **T34c**. It is allocated once, when the service is created, and never recomputed: it is in
 * somebody's `.env` and in a colleague's shell history by the end of the afternoon, so a
 * service that quietly moved between restarts would break both. A stopped service has it just
 * as a running one does, which is the point of reporting it here rather than only at creation.
 */
port?: number | null, 
/**
 * When it was last started, whether or not it is still running.
 */
last_started_at: Timestamp | null, 
/**
 * What its process exited with the last time one ended. [`None`] where the OS reported none —
 * a Unix process killed by a signal — for the same reason [`StateReason::Exited`] carries an
 * option there.
 */
last_exit_code: number | null, 
/**
 * What it declares it needs, as the graph holds it: each dependency once, in [`ServiceId`]
 * order. Empty for a service that depends on nothing.
 */
depends_on: Array<ServiceId>, };
