//! The modules MixDB is made of. One folder each, and one block of the list below each.

pub mod db;
pub mod mixengine;
pub mod rest;
pub mod terminal;
pub mod tools;

/// Every command of every module.
///
/// One list, because Tauri takes exactly one `invoke_handler` and `generate_handler!` needs its
/// paths written out rather than collected — but split into blocks by owner, and each block is
/// that module's own to edit.
///
/// Fixed to [`tauri::Wry`] rather than generic over the runtime: a command that takes an
/// `AppHandle` takes `AppHandle<Wry>`, which satisfies `CommandArg` for that one runtime and not
/// for an unknown `R`. `lib.rs` builds on `Wry` too, so nothing is given up by saying so here.
pub fn handler() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // ── shared ──
        crate::secrets::secrets_save,
        crate::secrets::secrets_load,
        crate::secrets::secrets_delete,
        crate::secrets::secrets_resolve_mixengine,
        crate::launch::launch_take_requests,
        // ── db ──
        db::commands::connect_db,
        db::commands::disconnect_db,
        db::commands::cancel_db_transfer,
        db::commands::test_ssh_tunnel,
        db::commands::tunnel_reconnect,
        db::commands::mysql::mysql_query,
        db::commands::mysql::mysql_list_databases,
        db::commands::mysql::mysql_server_info,
        db::commands::mysql::mysql_list_tables,
        db::commands::mysql::mysql_table_stats,
        db::commands::mysql::mysql_table_data,
        db::commands::mysql::mysql_update_row,
        db::commands::mysql::mysql_insert_rows,
        db::commands::mysql::mysql_delete_rows,
        db::commands::mysql::mysql_table_structure,
        db::commands::mysql::mysql_schema_outline,
        db::commands::mysql::mysql_collations,
        db::commands::mysql::mysql_dump,
        db::commands::mysql::mysql_restore,
        db::commands::mysql::mysql_drop_database,
        db::commands::mysql::mysql_create_database,
        db::commands::mysql::mysql_create_table,
        db::commands::mysql::mysql_rename_table,
        db::commands::mysql::mysql_drop_table,
        db::commands::mysql::mysql_add_column,
        db::commands::mysql::mysql_modify_column,
        db::commands::mysql::mysql_drop_column,
        db::commands::mysql::mysql_add_index,
        db::commands::mysql::mysql_modify_index,
        db::commands::mysql::mysql_drop_index,
        db::commands::mysql::mysql_run_script,
        db::commands::mysql::mysql_cancel_query,
        db::commands::mysql::mysql_validate_sql,
        db::commands::postgres::postgres_query,
        db::commands::postgres::postgres_list_databases,
        db::commands::postgres::postgres_server_info,
        db::commands::postgres::postgres_list_tables,
        db::commands::postgres::postgres_table_stats,
        db::commands::postgres::postgres_table_data,
        db::commands::postgres::postgres_update_row,
        db::commands::postgres::postgres_insert_rows,
        db::commands::postgres::postgres_delete_rows,
        db::commands::postgres::postgres_table_structure,
        db::commands::postgres::postgres_collations,
        db::commands::postgres::postgres_schema_outline,
        db::commands::postgres::postgres_run_script,
        db::commands::postgres::postgres_validate_sql,
        db::commands::postgres::postgres_cancel_query,
        db::commands::postgres::postgres_create_database,
        db::commands::postgres::postgres_drop_database,
        db::commands::postgres::postgres_create_table,
        db::commands::postgres::postgres_rename_table,
        db::commands::postgres::postgres_drop_table,
        db::commands::postgres::postgres_add_column,
        db::commands::postgres::postgres_modify_column,
        db::commands::postgres::postgres_drop_column,
        db::commands::postgres::postgres_add_index,
        db::commands::postgres::postgres_modify_index,
        db::commands::postgres::postgres_drop_index,
        db::commands::postgres::postgres_dump,
        db::commands::postgres::postgres_restore,
        db::commands::mongo::mongo_list_databases,
        db::commands::mongo::mongo_server_info,
        db::commands::mongo::mongo_list_collections,
        db::commands::mongo::mongo_collection_stats,
        db::commands::mongo::mongo_dump,
        db::commands::mongo::mongo_restore,
        db::commands::mongo::mongo_drop_database,
        db::commands::mongo::mongo_create_collection,
        db::commands::mongo::mongo_rename_collection,
        db::commands::mongo::mongo_drop_collection,
        db::commands::mongo::mongo_find,
        db::commands::mongo::mongo_collection_page,
        db::commands::mongo::mongo_next_ids,
        db::commands::mongo::mongo_insert_documents,
        db::commands::mongo::mongo_update_document,
        db::commands::mongo::mongo_delete_document,
        db::commands::redis::redis_command,
        db::commands::redis::redis_server_info,
        db::commands::redis::redis_list_databases,
        db::commands::redis::redis_select_db,
        db::commands::redis::redis_scan_keys,
        db::commands::redis::redis_key_value,
        db::commands::redis::redis_delete_keys,
        db::commands::sqlite::sqlite_create_file,
        db::commands::sqlite::sqlite_server_info,
        db::commands::sqlite::sqlite_list_databases,
        db::commands::sqlite::sqlite_list_tables,
        db::commands::sqlite::sqlite_table_data,
        db::commands::sqlite::sqlite_table_structure,
        db::commands::sqlite::sqlite_schema_outline,
        db::commands::sqlite::sqlite_table_stats,
        db::commands::sqlite::sqlite_collations,
        db::commands::sqlite::sqlite_update_row,
        db::commands::sqlite::sqlite_insert_rows,
        db::commands::sqlite::sqlite_delete_rows,
        db::commands::sqlite::sqlite_create_table,
        db::commands::sqlite::sqlite_rename_table,
        db::commands::sqlite::sqlite_drop_table,
        db::commands::sqlite::sqlite_add_column,
        db::commands::sqlite::sqlite_modify_column,
        db::commands::sqlite::sqlite_drop_column,
        db::commands::sqlite::sqlite_add_index,
        db::commands::sqlite::sqlite_modify_index,
        db::commands::sqlite::sqlite_drop_index,
        db::commands::sqlite::sqlite_run_script,
        db::commands::sqlite::sqlite_validate_sql,
        db::commands::sqlite::sqlite_dump,
        db::commands::sqlite::sqlite_restore,
        db::commands::clickhouse::clickhouse_server_info,
        db::commands::clickhouse::clickhouse_list_databases,
        db::commands::clickhouse::clickhouse_list_tables,
        db::commands::clickhouse::clickhouse_table_data,
        db::commands::clickhouse::clickhouse_table_structure,
        db::commands::clickhouse::clickhouse_table_stats,
        db::commands::clickhouse::clickhouse_schema_outline,
        db::commands::clickhouse::clickhouse_run_script,
        db::commands::clickhouse::clickhouse_validate_sql,
        db::commands::clickhouse::clickhouse_update_row,
        db::commands::clickhouse::clickhouse_delete_rows,
        db::commands::clickhouse::clickhouse_insert_rows,
        db::commands::clickhouse::clickhouse_create_database,
        db::commands::clickhouse::clickhouse_drop_database,
        db::commands::clickhouse::clickhouse_create_table,
        db::commands::clickhouse::clickhouse_rename_table,
        db::commands::clickhouse::clickhouse_drop_table,
        db::commands::clickhouse::clickhouse_add_column,
        db::commands::clickhouse::clickhouse_drop_column,
        db::commands::clickhouse::clickhouse_modify_column,
        db::commands::clickhouse::clickhouse_add_skip_index,
        db::commands::clickhouse::clickhouse_modify_skip_index,
        db::commands::clickhouse::clickhouse_drop_skip_index,
        db::commands::clickhouse::clickhouse_rebuild_order_by,
        db::commands::clickhouse::clickhouse_row_count,
        db::commands::clickhouse::clickhouse_dump,
        db::commands::clickhouse::clickhouse_restore,
        db::commands::mssql::mssql_list_databases,
        db::commands::mssql::mssql_server_info,
        db::commands::mssql::mssql_list_tables,
        db::commands::mssql::mssql_table_data,
        db::commands::mssql::mssql_table_structure,
        db::commands::mssql::mssql_table_stats,
        db::commands::mssql::mssql_collations,
        db::commands::mssql::mssql_schema_outline,
        db::commands::mssql::mssql_update_row,
        db::commands::mssql::mssql_insert_rows,
        db::commands::mssql::mssql_delete_rows,
        db::commands::mssql::mssql_run_script,
        db::commands::mssql::mssql_cancel_query,
        db::commands::mssql::mssql_validate_sql,
        db::commands::mssql::mssql_create_database,
        db::commands::mssql::mssql_drop_database,
        db::commands::mssql::mssql_create_table,
        db::commands::mssql::mssql_rename_table,
        db::commands::mssql::mssql_drop_table,
        db::commands::mssql::mssql_add_column,
        db::commands::mssql::mssql_drop_column,
        db::commands::mssql::mssql_modify_column,
        db::commands::mssql::mssql_add_index,
        db::commands::mssql::mssql_modify_index,
        db::commands::mssql::mssql_drop_index,
        db::commands::mssql::mssql_dump,
        db::commands::mssql::mssql_restore,
        db::commands::tools::dumptools_status,
        db::commands::tools::dumptools_ready,
        db::commands::tools::dumptools_downloadable,
        db::commands::tools::dumptools_install,
        db::commands::tools::dumptools_uninstall,
        db::commands::tools::dumptools_set_path,
        db::commands::handoff::handoff_take,
        // ── rest ──
        rest::commands::rest_send,
        rest::commands::rest_cancel,
        rest::commands::rest_preview_open,
        rest::commands::rest_preview_close,
        // ── terminal ──
        terminal::commands::terminal_local_shells,
        terminal::commands::terminal_open,
        terminal::commands::terminal_write,
        terminal::commands::terminal_resize,
        terminal::commands::terminal_close,
        // ── tools ──
        tools::commands::tools_listening_ports,
    ]
}
